config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :converts
  resources :facul

  root 'facul#index'

end

app/models/converter.rb
class Converter
  BINARY      = 'Binary'
  DECIMAL     = 'Decimal'
  HEXADECIMAL = 'Hexadecimal'
  OCTAL       = 'OCTAL'

  attr_reader :text, :source, :target

  def initialize(options)
    @text = options[:text]
    @source = options[:source]
    @target = options[:target]
    @encrypt = options[:encrypt]
  end

  def convert
    case target
    when BINARY
      result = to_binary(text)
    when DECIMAL
      result = to_decimal(result)
    when OCTAL
      result = to_octal(text)
    when HEXADECIMAL
      result = to_hex(text)
    else
      result = text
    end

    result
  end

  private

  def binary_to_decimal(text)
    bintodec_array = text.split ''
    i = 0
    result = 0
    bintodec_array.each do |char|
      char = char.to_i
      if char == 1 || char == 0
        result = 2 * i
        i = char.to_i + result
      else
        return "ERROR"
      end
    end
    result
  end

  def octal_to_decimal(text)
    octaltodec_array = text.split ''
    per = octaltodec_array.count
    total = 0
    octaltodec_array.each do |char|
      per = per - 1
      calc2 = char.to_i * 8 ** per
      total = total + calc2
    end
    total
  end

  def hex_to_decimal(text)
    hextodec_array = text.split ''
    per = hextodec_array.count
    total = 0
    hextodec_array.each do |char|
      case char
      when "A"
        char = 10
      when "B"
        char = 11
      when "C"
        char = 12
      when "D"
        char = 13
      when "E"
        char = 14
      when "F"
        char = 15
      end
      if char == ("G".."Z").to_a
        return "ERROR"
      end
      per = per - 1
      calc2 = char.to_i * 16 ** per
      total = total + calc2
    end
    total
  end


  def to_decimal(text)
    text = text.split ''
    convert_decimal = []
    text.each do |decimal|
      convert_decimal << ' ' + decimal.ord.to_s
    end
    convert_decimal.join
  end

  def to_binary(text)
    bin_array = text.split ''
    bin_array.map do |binary|
      revert = []
      binary = binary.ord
      (1..8).each do
        rest = binary % 2
        binary = binary / 2
        revert << rest
      end
      revert.reverse << ' '
    end.join
  end

  def to_octal(text)
    octal_array = text.split ''
    octal_array.map do |octal|
      revert = []
      octal = octal.ord
      (1..3).each do
        rest = octal % 8
        octal = octal / 8
        revert << rest
      end
      revert.reverse << ' '
    end.join
  end

  def to_hex(text)
    hex_array = text.split ''
    hex_array.map do |hex|
      revert = []
      hex = hex.ord
      (1..2).each do
        rest = hex % 16
        hex = hex / 16

        if rest == 10
          revert << "A"
        elsif rest == 11
          revert << "B"
        elsif rest == 12
          revert << "C"
        elsif rest == 13
          revert << "D"
        elsif rest == 14
          revert << "E"
        elsif rest == 15
          revert << "F"
        else
          revert << rest
        end
      end
      revert.reverse << ' '
    end.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/converts_controller.rb
class ConvertsController < ApplicationController
  before_action :set_convert, only: [:show, :edit, :update, :destroy]

  # GET /converts
  # GET /converts.json
  def index
    @converts = Convert.all
  end

  # GET /converts/1
  # GET /converts/1.json
  def show
  end

  # GET /converts/new
  def new
    @convert = Convert.new
  end

  # GET /converts/1/edit
  def edit
  end

  # POST /converts
  # POST /converts.json
  def create
    @convert = Convert.new(convert_params)

    respond_to do |format|
      if @convert.save
        format.html { redirect_to @convert, notice: 'Convert was successfully created.' }
        format.json { render :show, status: :created, location: @convert }
      else
        format.html { render :new }
        format.json { render json: @convert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /converts/1
  # PATCH/PUT /converts/1.json
  def update
    respond_to do |format|
      if @convert.update(convert_params)
        format.html { redirect_to @convert, notice: 'Convert was successfully updated.' }
        format.json { render :show, status: :ok, location: @convert }
      else
        format.html { render :edit }
        format.json { render json: @convert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /converts/1
  # DELETE /converts/1.json
  def destroy
    @convert.destroy
    respond_to do |format|
      format.html { redirect_to converts_url, notice: 'Convert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convert
      @convert = Convert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def convert_params
      params.require(:convert).permit(:name, :description, :picture)
    end
end

app/controllers/facul_controller.rb
class FaculController < ApplicationController
  def index
  end

  def create
    options = {
      text: params[:text],
      source: params[:base_insert],
      target: params[:base_view],
      encrypt: params[:base_encrypt] == 'Sim'
    }

    converter = Converter.new(options)
    @result = converter.convert

    render :index
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converts_helper.rb
module ConvertsHelper
end

app/helpers/facul_helper.rb
module FaculHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/converts/_form.html.erb
<%= form_for(@convert) do |f| %>
  <% if @convert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convert.errors.count, "error") %> prohibited this convert from being saved:</h2>

      <ul>
      <% @convert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/converts/edit.html.erb
<h1>Editing Convert</h1>

<%= render 'form' %>

<%= link_to 'Show', @convert %> |
<%= link_to 'Back', converts_path %>

app/views/converts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Converts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @converts.each do |convert| %>
      <tr>
        <td><%= convert.name %></td>
        <td><%= convert.description %></td>
        <td><%= convert.picture %></td>
        <td><%= link_to 'Show', convert %></td>
        <td><%= link_to 'Edit', edit_convert_path(convert) %></td>
        <td><%= link_to 'Destroy', convert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Convert', new_convert_path %>

app/views/converts/new.html.erb
<h1>New Convert</h1>

<%= render 'form' %>

<%= link_to 'Back', converts_path %>

app/views/converts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @convert.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @convert.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @convert.picture %>
</p>

<%= link_to 'Edit', edit_convert_path(@convert) %> |
<%= link_to 'Back', converts_path %>

app/views/facul/index.html.erb
<h1>
  <center>
    Conversão entre bases.
  </center>
</h1>

<table class="table-style" align="center">
  <tr>
    <th class="colum-style">
        <%= form_tag do %>
        
          <h3> Informe o texto a ser convertido: </h3>
          <%= text_field_tag 'text', nil, maxlength: 16, class: "text_class" %>

          <h3> Os caracteres mencionados pertences a qual base? </h3>
          <%= radio_button_tag(:base_insert, "Binary",  class: "binary_radio_insert") %>
          <span> Binario </span><br/>
          <%= radio_button_tag(:base_insert, "Decimal") %>
          <span> Decimal (Texto)</span><br/>
          <%= radio_button_tag(:base_insert, "Octal") %>
          <span> Octal </span><br/>
          <%= radio_button_tag(:base_insert, "Hexadecimal") %>
          <span> Hexadecimal </span><br/>

          <h3>Para qual base gostaria de converter? </h3>
          <%= radio_button_tag(:base_view, "Binary") %>
          <span> Binario </span><br/>
          <%= radio_button_tag(:base_view, "Decimal") %>
          <span> Decimal </span><br/>
          <%= radio_button_tag(:base_view, "Octal") %>
          <span> Octal </span><br/>
          <%= radio_button_tag(:base_view, "Hexadecimal") %>
          <span> Hexadecimal </span><br/>

          <h3> Deseja criptografar? </h3>
          <%= radio_button_tag(:base_encrypt, "Sim") %>
          <span> Sim </span><br/>
          <%= radio_button_tag(:base_encrypt, "Não") %>
          <span> Não </span><br/>

          <p><%= submit_tag("Converter") %></p>
        
        <% end %>
    </th>
    <th class="colum-style">
      <span>Texto convertido: </span>
      <%= text_area_tag(:output, @result, :readonly => true, size: "60x5") %>
      <span>Texto Criptografado: </span>
      <%= text_area_tag(:output, @convert_insert , :readonly => true, size: "60x5") %>
    </th>
  </tr>
  <th colspan="2" align="left">
    <%= form_tag do %>
      <span>Texto criptografado? Descriptografe! </span>
       <%= text_field_tag 'decrypt', '', size: 60 %>
       <%= submit_tag("Decrypt") %>
       <span>Texto Original: </span>
       <%= text_field_tag 'decrypt', '', size: 16, maxlength: 16, :readonly => true %>
      
    <% end -%>
    <p>
  </th>
</table>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>
  <center>Conversão entre bases</center>
</h1>

<table class="table-style" align="center">
  <tr>
    <th class="colum-style">
      <div id="text_insert">

        <h3>
          Informe o texto a ser convertido:
        </h3>

        <input type="text" maxlength="16">

        <h3>
          Qual a base do texto mencionado?
        </h3>

        <p><input type="radio" name="base_insert" id="binary_insert">
        <span> Binario </span>
        <p><input type="radio" name="base_insert" id="decimal_insert">
        <span> Decimal </span>
        <p><input type="radio" name="base_insert" id="octal_insert">
        <span> Octal </span>
        <p><input type="radio" name="base_insert" id="hex_insert"> 
        <span> Hexadecimal </span>
        <p><input type="radio" name="base_insert" id="text_insert">
        <span> Texto </span>
        </br>
        </br>

        <h3>
          Para qual base gostaria de converter?
        </h3>

        <p><input type="radio" name="base_view" id="binary_view">
        <span> Binario </span>
        <p><input type="radio" name="base_view" id="decimal_view">
        <span> Decimal </span>
        <p><input type="radio" name="base_view" id="octal_view">
        <span> Octal </span>
        <p><input type="radio" name="base_view" id="hex_view">
        <span> Hexadecimal </span>
        <p>
        <input type="submit" value="Converter">
      </div>
    </th>

    <th class="colum-style">
      <span>Texto convertido: </span>
      <p></p><textarea rows="10" cols="60" readonly>
      </textarea>
    </th>
  </tr>
</table>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facul</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield %>
</body>
</html>